name: Deploy test

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Maven
        uses: stCarolas/setup-maven@v3
        with:
          maven-version: 3.5.4
      - name: Run tests
        run: mvn --batch-mode clean test -f benito-backend/pom.xml
      - name: Build
        run: ./build test
      - name: Install
        run: mvn --batch-mode install -f benito-backend/pom.xml -Dmaven.test.skip=true
      - name: Deploy to heroku
        env:
          HEROKU_API_KEY=HEROKU_API_KEY: ${{ secrets.BENITO_API_KEY }}
        run: mvn -X --batch-mode heroku:deploy -f benito-backend/pom.xml -Dmaven.test.skip=true -Dheroku.appName=benito-test

