name: Deploy to prod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: mvn --batch-mode clean test -f benito-backend/pom.xml
      - name: Kill server
        run: sshpass -p ${{secrets.REMOTE_PASSWORD}} ssh -f "benito/shutdown"
      - name: Checkout changes
        run: sshpass -p ${{secrets.REMOTE_PASSWORD}} ssh -f "git -C /root/benito pull origin master"
      - name: Build
        run: sshpass -p ${{secrets.REMOTE_PASSWORD}} ssh -f "benito/build prod"
      - name: Start server
        run: sshpass -p ${{secrets.REMOTE_PASSWORD}} ssh -f "benito/startup"

