name: Deploy to prod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: mvn --batch-mode clean test -f benito-backend/pom.xml
      - name: Kill server
        uses: appleboy/ssh-action@master
        with:
          host: proyectate.tk
          username: root
          password: ${{secrets.REMOTE_PASSWORD}}
          script: benito/shutdown
      - name: Checkout changes
        uses: appleboy/ssh-action@master
        with:
          host: proyectate.tk
          username: root
          password: ${{secrets.REMOTE_PASSWORD}}
          script: git -C /root/benito pull origin master
      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: proyectate.tk
          username: root
          password: ${{secrets.REMOTE_PASSWORD}}
          script: benito/build prod
      - name: Start server
        uses: appleboy/ssh-action@master
        with:
          host: proyectate.tk
          username: root
          password: ${{secrets.REMOTE_PASSWORD}}
          script: benito/startup prod

