name: Deploy test

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: ./build staging
        run: mvn --batch-mode clean test -f benito-backend/pom.xml
        run: HEROKU_API_KEY="${{secrets.BENITO_API_KEY}}" mvn heroku:deploy
